version: "3"
# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
# https://github.com/pi-hole/docker-pi-hole#environment-variables
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ:'Europe/London'
      - WEBPASSWORD=${WEB_PASSWORD}
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
